require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # 許可するホスト（localhost・backend。docker compose の他のコンテナ（frontend・relay）が、サービス名 backend で呼ぶ）は、
  # config/allowed_hosts.rb が持ち、config/application.rb が config.hosts へ入れる（環境ごとの一覧を、1 か所に集める）

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # SQL のコメントに実行時の情報（タグ）を付ける設定は、無効にする（issue #8 で変更）。有効にすると、Rails は prepared statements を
  # 無効にし、SQL の文に値が直接入る。ログの SQL に、Google の利用者識別子（sub）・配信のタイトル・暗号化したトークンなどが、
  # そのまま出てしまう（prepared statements では、機密の列の値は、filter_attributes で [FILTERED] になる。本番・テストと同じ挙動にそろえる）。
  # spec/config/development_sql_log_spec.rb が、有効にしていないことを検査する。
  config.active_record.query_log_tags_enabled = false

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
